# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20180207_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('priviledge', models.IntegerField(default=100)),
            ],
        ),
        migrations.AlterField(
            model_name='income',
            name='customer_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Job'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='balance',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='vip',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='vip',
            name='phone',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
