# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-10 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20180208_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='if_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
