# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20180210_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='staff',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='accounting.Staff'),
            preserve_default=False,
        ),
    ]
