# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_systemuser_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='item_no',
            field=models.IntegerField(default=1),
        ),
    ]
