# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_service_item_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='promote_ratio',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=25),
            preserve_default=False,
        ),
    ]
