# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_vip_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
