# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_auto_20180214_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='holder',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
