# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_income_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='income',
            name='total',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='service',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Staff'),
        ),
    ]
