# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_auto_20180215_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='item_no',
            field=models.DecimalField(decimal_places=15, default=1.0, max_digits=25),
        ),
    ]
