# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-18 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_vippayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='vip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.VIP'),
        ),
    ]
