# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-18 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_income_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPTopupRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.SystemUser')),
                ('vip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.VIP')),
            ],
        ),
    ]
