# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-18 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_viptopuprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='viptopuprecord',
            name='note',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
