# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_viptopuprecord_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='gender',
            field=models.BooleanField(default=False),
        ),
    ]
