# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_income_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Item'),
        ),
    ]
