# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_auto_20180220_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='recorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.SystemUser'),
        ),
    ]
