# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-01 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_viptopuprecord_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
