# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_auto_20180301_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
