# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-25 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_income_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deleter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleter', to='accounting.SystemUser'),
        ),
        migrations.AlterField(
            model_name='service',
            name='recorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recorder', to='accounting.SystemUser'),
        ),
    ]
