# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_auto_20180325_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=15, default=0.0, max_digits=25)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Income')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.PaymentMethod')),
            ],
        ),
        migrations.CreateModel(
            name='MultiPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.PaymentMethod')),
            ],
        ),
    ]
