# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_multiincome_multipayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiincome',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
