# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-02 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_multiincome_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='viptopuprecord',
            name='amount',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=25),
        ),
    ]
